server {
    listen 80;
    listen [::]:80;

    server_name 160.25.226.152 server.saifulinfo.com;

    root /var/www/airpurifying-concrete;
    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /presentation/ {
        try_files $uri $uri/ /presentation/index.html;
    }

    # API routes for PHP
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
